"""phase 4: vendor and procurement domain

Revision ID: 0dcb263b355d
Revises: c139ab39be59
Create Date: 2026-08-13 12:00:19.068999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dcb263b355d'
down_revision: Union[str, None] = 'c139ab39be59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('VENDOR_TO_WAREHOUSE', 'WAREHOUSE_TO_VENDOR', name='freight_direction'), nullable=False),
    sa.Column('linked_type', sa.Enum('shipment', 'vendor_return', name='freight_linked_type'), nullable=False),
    sa.Column('linked_id', sa.UUID(), nullable=False),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('payer', sa.Enum('vendor', 'warehouse', name='freight_payer_party'), server_default='vendor', nullable=False),
    sa.Column('base_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_on_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('net_payable_to_transporter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_liability_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gta_forward_charge', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Paid', 'Overdue', name='freight_payment_status'), server_default='Pending', nullable=False),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfqs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('return_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.Column('delivery_location', sa.String(length=500), nullable=True),
    sa.Column('specifications', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('Draft', 'Sent', 'Awaiting Quotations', 'Partially Responded', 'Ready for Comparison', 'Vendor Selected', 'Purchase Order Generated', 'Closed', name='rfq_status'), server_default='Draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['store_returns.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_pr_id'), 'rfqs', ['pr_id'], unique=False)
    op.create_index(op.f('ix_rfqs_ref_code'), 'rfqs', ['ref_code'], unique=True)
    op.create_index(op.f('ix_rfqs_return_id'), 'rfqs', ['return_id'], unique=False)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('gst', sa.String(length=15), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_holder', sa.String(length=255), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=20), nullable=True),
    sa.Column('bank_branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pending Approval', 'Active', 'Rejected', 'Suspended', 'Blocked', name='vendor_status'), server_default='Pending Approval', nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('registered_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst'),
    sa.UniqueConstraint('pan')
    )
    op.create_index(op.f('ix_vendors_code'), 'vendors', ['code'], unique=True)
    op.create_table('quotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('warranty', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('freight_payer', sa.Enum('vendor', 'warehouse', name='freight_payer'), nullable=False),
    sa.Column('freight_details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('Submitted', 'Under Evaluation', 'Approved', 'Rejected', name='quotation_status'), server_default='Submitted', nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfq_invited_vendors',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rfq_id', 'vendor_id')
    )
    op.create_table('vendor_categories',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id', 'category')
    )
    op.create_table('vendor_compliance_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('gstCert', 'pan', 'businessLicense', 'msme', 'iso', name='compliance_doc_type'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_goods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('Fabric', 'Trims', 'Packaging', 'Other', name='goods_category'), nullable=False),
    sa.Column('unit', sa.Enum('Meters', 'Pcs', 'Kg', 'Rolls', name='goods_unit'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stock_status', sa.Enum('In Stock', 'Low Stock', 'Out of Stock', name='goods_stock_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('received_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('Pending Acceptance', 'Accepted', 'In Production', 'Ready to Ship', 'Delivered', 'Rejected', name='purchase_order_status'), server_default='Pending Acceptance', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_quotation_id'), 'purchase_orders', ['quotation_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_ref_code'), 'purchase_orders', ['ref_code'], unique=True)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('vendor_catalog_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('goods_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('fabric', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('gsm', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku_variant_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('Submitted', 'SKU Assigned', name='catalog_submission_status'), server_default='Submitted', nullable=False),
    sa.Column('submitted_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['vendor_goods.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('draft_status', sa.Enum('Draft', 'Submitted', name='asn_draft_status'), server_default='Draft', nullable=False),
    sa.Column('transport_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asns_ref_code'), 'asns', ['ref_code'], unique=True)
    op.create_table('vendor_catalog_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['vendor_catalog_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asn_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('uploaded_by_role', sa.Enum('vendor', 'warehouse', name='asn_attachment_uploader_role'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asn_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=True),
    sa.Column('ordered_qty', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('accepted_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('inspection_status', sa.Enum('awaiting_inspection', 'accepted', 'partial', 'rejected', name='asn_inspection_status'), server_default='awaiting_inspection', nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asn_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('freight_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='invoice_status'), server_default='pending', nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'invoice_number', name='uq_invoice_vendor_number')
    )
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=False),
    sa.Column('dispatch_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_contact', sa.String(length=20), nullable=True),
    sa.Column('vehicle_no', sa.String(length=20), nullable=True),
    sa.Column('tracking_no', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Packed', 'Dispatched', 'In Transit', 'Delivered', 'Delayed', name='shipment_status'), server_default='Packed', nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('asn_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Initiated', 'Approved', 'In Transit', 'Received', 'Refunded', 'Rejected', name='vendor_return_status'), server_default='Initiated', nullable=False),
    sa.Column('review_remarks', sa.Text(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('vehicle_no', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_contact', sa.String(length=20), nullable=True),
    sa.Column('tracking_no', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asn_id'], ['asns.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_returns_asn_id'), 'vendor_returns', ['asn_id'], unique=False)
    op.create_index(op.f('ix_vendor_returns_po_id'), 'vendor_returns', ['po_id'], unique=False)
    op.create_index(op.f('ix_vendor_returns_ref_code'), 'vendor_returns', ['ref_code'], unique=True)
    op.create_index(op.f('ix_vendor_returns_sku_variant_id'), 'vendor_returns', ['sku_variant_id'], unique=False)
    op.create_index(op.f('ix_vendor_returns_status'), 'vendor_returns', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_returns_vendor_id'), 'vendor_returns', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_returns_warehouse_id'), 'vendor_returns', ['warehouse_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('po_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('Paid', 'Pending', 'Overdue', 'Processing', name='payment_status'), server_default='Pending', nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_mode', sa.Enum('NEFT', 'RTGS', 'Cheque', 'IMPS', name='payment_mode'), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_return_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_return_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['vendor_return_id'], ['vendor_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Note: uq_sku_supplying_vendors is NOT (re-)created here — Phase 3's migration already
    # created it (it's part of SkuSupplyingVendor's original __table_args__); autogenerate's
    # diff spuriously flagged it again here after vendor_id changed from a plain column to a
    # real FK, but the constraint on disk is already correct and doesn't need touching twice.
    # Explicit names (autogenerate left these anonymous) so downgrade's drop_constraint calls
    # below can actually reference them — an anonymous constraint name can't be reversed.
    op.create_foreign_key('fk_sku_supplying_vendors_vendor_id', 'sku_supplying_vendors', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_store_returns_resolution_rfq_id', 'store_returns', 'rfqs', ['resolution_rfq_id'], ['id'])
    op.create_foreign_key('fk_warehouse_vendor_links_vendor_id', 'warehouse_vendor_links', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_warehouse_vendor_links_vendor_id', 'warehouse_vendor_links', type_='foreignkey')
    op.drop_constraint('fk_store_returns_resolution_rfq_id', 'store_returns', type_='foreignkey')
    op.drop_constraint('fk_sku_supplying_vendors_vendor_id', 'sku_supplying_vendors', type_='foreignkey')
    op.drop_table('vendor_return_attachments')
    op.drop_table('shipment_timeline_events')
    op.drop_table('payments')
    op.drop_index(op.f('ix_vendor_returns_warehouse_id'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_vendor_id'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_status'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_sku_variant_id'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_ref_code'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_po_id'), table_name='vendor_returns')
    op.drop_index(op.f('ix_vendor_returns_asn_id'), table_name='vendor_returns')
    op.drop_table('vendor_returns')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('goods_receipts')
    op.drop_table('asn_items')
    op.drop_table('asn_attachments')
    op.drop_table('vendor_catalog_documents')
    op.drop_index(op.f('ix_asns_ref_code'), table_name='asns')
    op.drop_table('asns')
    op.drop_table('vendor_catalog_submissions')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_ref_code'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_quotation_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('vendor_goods')
    op.drop_table('vendor_compliance_documents')
    op.drop_table('vendor_categories')
    op.drop_table('rfq_invited_vendors')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_vendors_code'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_return_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_ref_code'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_pr_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_table('freight_payments')
    # ### end Alembic commands ###
    # Postgres ENUM types created by the sa.Enum(...) columns above — drop_table alone doesn't
    # remove these, and autogenerate doesn't emit the drop on its own either.
    for enum_name in (
        'vendor_return_status', 'freight_payment_status', 'freight_payer_party', 'freight_linked_type',
        'freight_direction', 'payment_mode', 'payment_status', 'invoice_status', 'shipment_status',
        'asn_inspection_status', 'asn_attachment_uploader_role', 'asn_draft_status', 'purchase_order_status',
        'freight_payer', 'quotation_status', 'rfq_status', 'catalog_submission_status', 'goods_stock_status',
        'goods_unit', 'goods_category', 'compliance_doc_type', 'vendor_status',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
