"""phase 3: core-ops domain

Revision ID: c139ab39be59
Revises: 39313222eda2
Create Date: 2026-08-13 11:50:47.434242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c139ab39be59'
down_revision: Union[str, None] = '39313222eda2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portal_type', sa.Enum('super_admin', 'warehouse', 'vendor', 'store', name='audit_portal_type'), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_portal_type'), 'audit_log', ['portal_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('style_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('fabric', sa.String(length=100), nullable=True),
    sa.Column('gsm', sa.String(length=20), nullable=True),
    sa.Column('hsn', sa.String(length=20), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), server_default='Pcs', nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='sku_status'), server_default='active', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_category'), 'skus', ['category'], unique=False)
    op.create_index(op.f('ix_skus_status'), 'skus', ['status'], unique=False)
    op.create_index(op.f('ix_skus_style_code'), 'skus', ['style_code'], unique=True)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('store_type', sa.Enum('Flagship', 'Standard', 'Outlet', name='store_type'), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('years_in_operation', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('manager_user_id', sa.UUID(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='20', nullable=False),
    sa.Column('status', sa.Enum('Pending Approval', 'Active', 'Rejected', 'Inactive', 'Blocked', name='store_status'), server_default='Pending Approval', nullable=False),
    sa.Column('opened_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_code'), 'stores', ['code'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('tax_jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('license_no', sa.String(length=50), nullable=True),
    sa.Column('capacity_sqft', sa.Integer(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('working_days', sa.String(length=50), nullable=True),
    sa.Column('low_stock_warning_units', sa.Integer(), nullable=True),
    sa.Column('critical_stock_warning_units', sa.Integer(), nullable=True),
    sa.Column('operating_hours_from', sa.Time(), nullable=True),
    sa.Column('operating_hours_to', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('Pending Approval', 'Active', 'Rejected', 'Suspended', 'Blocked', name='warehouse_status'), server_default='Pending Approval', nullable=False),
    sa.Column('registered_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('sku_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('variant_code', sa.String(length=40), nullable=False),
    sa.Column('colour', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_variants_variant_code'), 'sku_variants', ['variant_code'], unique=True)
    op.create_table('store_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'approved', name='store_approval_status'), server_default='waiting', nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_store_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='warehouse_store_link_status'), server_default='active', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'store_id', name='uq_warehouse_store_links')
    )
    op.create_table('warehouse_vendor_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='warehouse_vendor_link_status'), server_default='active', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'vendor_id', name='uq_warehouse_vendor_links')
    )
    op.create_table('warehouse_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('utilized_units', sa.Integer(), server_default='0', nullable=False),
    sa.Column('product_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available', sa.Integer(), server_default='0', nullable=False),
    sa.Column('returns_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'sku_variant_id')
    )
    op.create_table('purchase_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('requested_qty', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('required_by', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('High', 'Medium', 'Low', name='purchase_request_priority'), server_default='Medium', nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'declined', name='purchase_request_approval_status'), server_default='pending', nullable=False),
    sa.Column('fulfilment_type', sa.Enum('stock', 'rfq', 'split', name='fulfilment_type'), nullable=True),
    sa.Column('fulfilment_ref_type', sa.Enum('transfer_order', 'rfq', name='fulfilment_ref_type'), nullable=True),
    sa.Column('fulfilment_ref_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_ref_code'), 'purchase_requests', ['ref_code'], unique=True)
    op.create_table('sku_supplying_vendors',
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sku_variant_id', 'vendor_id'),
    sa.UniqueConstraint('sku_variant_id', 'vendor_id', name='uq_sku_supplying_vendors')
    )
    op.create_table('store_discounts',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'sku_variant_id')
    )
    op.create_table('store_inventory',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'sku_variant_id')
    )
    op.create_table('store_product_settings',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', 'sku_variant_id')
    )
    op.create_table('warehouse_sku_status',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='warehouse_sku_status_value'), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'sku_variant_id')
    )
    op.create_table('warehouse_stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('Inbound', 'Outbound', 'Transfer', 'Adjustment', 'Return', name='warehouse_movement_type'), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='Pcs', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('return_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('Warehouse Stock', 'Vendor Procurement', 'Return Replenishment', 'Combined Stock + Vendor', name='transfer_order_source_type'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Dispatched', 'Delivered', 'Completed', name='transfer_order_status'), server_default='Pending', nullable=False),
    sa.Column('transporter', sa.String(length=100), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=True),
    sa.Column('tracking_number', sa.String(length=50), nullable=True),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['store_returns.id'], name='fk_transfer_orders_return_id', use_alter=True),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_orders_pr_id'), 'transfer_orders', ['pr_id'], unique=False)
    op.create_index(op.f('ix_transfer_orders_ref_code'), 'transfer_orders', ['ref_code'], unique=True)
    op.create_index(op.f('ix_transfer_orders_return_id'), 'transfer_orders', ['return_id'], unique=False)
    op.create_index(op.f('ix_transfer_orders_status'), 'transfer_orders', ['status'], unique=False)
    op.create_table('store_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision', sa.Enum('replenish', 'writeoff', name='store_return_decision'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'replenished', 'dispatched', 'writtenoff', name='store_return_status'), server_default='pending', nullable=False),
    sa.Column('resolution_transfer_order_id', sa.UUID(), nullable=True),
    sa.Column('resolution_rfq_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['resolution_transfer_order_id'], ['transfer_orders.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_returns_ref_code'), 'store_returns', ['ref_code'], unique=True)
    # `transfer_orders.return_id` was declared with use_alter=True to break the transfer_orders
    # <-> store_returns creation-order cycle — Alembic's autogenerate correctly omits it from
    # the inline CREATE TABLE above but does NOT emit the deferred ADD CONSTRAINT on its own
    # (a known Alembic autogenerate gap with circular FKs), so it's added explicitly here.
    op.create_foreign_key(
        'fk_transfer_orders_return_id', 'transfer_orders', 'store_returns', ['return_id'], ['id']
    )
    op.create_table('inventory_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('return_id', sa.UUID(), nullable=True),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('vendor_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['store_returns.id'], ),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_reservations_pr_id'), 'inventory_reservations', ['pr_id'], unique=False)
    op.create_index(op.f('ix_inventory_reservations_return_id'), 'inventory_reservations', ['return_id'], unique=False)
    op.create_table('receiving_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_order_id', sa.UUID(), nullable=False),
    sa.Column('sku_variant_id', sa.UUID(), nullable=False),
    sa.Column('expected_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Verified', 'Return Requested', 'Written Off', name='receiving_item_status'), server_default='Pending', nullable=False),
    sa.Column('condition', sa.Enum('Good', 'Missing/Defective', name='receiving_item_condition'), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('issue_qty', sa.Integer(), nullable=True),
    sa.Column('issue_note', sa.Text(), nullable=True),
    sa.Column('return_type', sa.Enum('Replenishment', 'Write-off', name='receiving_return_type'), nullable=True),
    sa.Column('store_return_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_variant_id'], ['sku_variants.id'], ),
    sa.ForeignKeyConstraint(['store_return_id'], ['store_returns.id'], ),
    sa.ForeignKeyConstraint(['transfer_order_id'], ['transfer_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receiving_items_sku_variant_id'), 'receiving_items', ['sku_variant_id'], unique=False)
    op.create_index(op.f('ix_receiving_items_transfer_order_id'), 'receiving_items', ['transfer_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receiving_items_transfer_order_id'), table_name='receiving_items')
    op.drop_index(op.f('ix_receiving_items_sku_variant_id'), table_name='receiving_items')
    op.drop_table('receiving_items')
    op.drop_index(op.f('ix_inventory_reservations_return_id'), table_name='inventory_reservations')
    op.drop_index(op.f('ix_inventory_reservations_pr_id'), table_name='inventory_reservations')
    op.drop_table('inventory_reservations')
    op.drop_constraint('fk_transfer_orders_return_id', 'transfer_orders', type_='foreignkey')
    op.drop_index(op.f('ix_store_returns_ref_code'), table_name='store_returns')
    op.drop_table('store_returns')
    op.drop_index(op.f('ix_transfer_orders_status'), table_name='transfer_orders')
    op.drop_index(op.f('ix_transfer_orders_return_id'), table_name='transfer_orders')
    op.drop_index(op.f('ix_transfer_orders_ref_code'), table_name='transfer_orders')
    op.drop_index(op.f('ix_transfer_orders_pr_id'), table_name='transfer_orders')
    op.drop_table('transfer_orders')
    op.drop_table('warehouse_stock_movements')
    op.drop_table('warehouse_sku_status')
    op.drop_table('store_product_settings')
    op.drop_table('store_inventory')
    op.drop_table('store_discounts')
    op.drop_table('sku_supplying_vendors')
    op.drop_index(op.f('ix_purchase_requests_ref_code'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_table('inventory')
    op.drop_table('warehouse_zones')
    op.drop_table('warehouse_vendor_links')
    op.drop_table('warehouse_store_links')
    op.drop_table('store_approvals')
    op.drop_index(op.f('ix_sku_variants_variant_code'), table_name='sku_variants')
    op.drop_table('sku_variants')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_stores_code'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_skus_style_code'), table_name='skus')
    op.drop_index(op.f('ix_skus_status'), table_name='skus')
    op.drop_index(op.f('ix_skus_category'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_portal_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    # Postgres ENUM types created by the sa.Enum(...) columns above — drop_table alone doesn't
    # remove these, and autogenerate doesn't emit the drop on its own either.
    for enum_name in (
        'receiving_return_type', 'receiving_item_condition', 'receiving_item_status',
        'store_return_status', 'store_return_decision', 'transfer_order_status',
        'transfer_order_source_type', 'fulfilment_ref_type', 'fulfilment_type',
        'purchase_request_approval_status', 'purchase_request_priority', 'warehouse_movement_type',
        'warehouse_sku_status_value', 'store_approval_status', 'warehouse_vendor_link_status',
        'warehouse_store_link_status', 'warehouse_status', 'store_type', 'store_status',
        'sku_status', 'audit_portal_type',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
